/* Generated by Yosys 0.57 (git sha1 3aca86049e79a165932e3e7660358376f45acaed, clang++ 17.0.0 -fPIC -O3) */

module \$paramod$0a04d2ca855f7a52b7b0f8269f16a7f2c6677e46\RAM16 (CLK, WE0, EN0, A0, Di0, Do0);
  input CLK;
  wire CLK;
  input [3:0] WE0;
  wire [3:0] WE0;
  input EN0;
  wire EN0;
  input [3:0] A0;
  wire [3:0] A0;
  input [31:0] Di0;
  wire [31:0] Di0;
  output [31:0] Do0;
  wire [31:0] Do0;
  wire [3:0] A0_buf;
  wire CLK_buf;
  wire [31:0] Di0_buf;
  wire [31:0] Do0_pre;
  wire EN0_buf;
  wire [1:0] SEL0;
  wire [3:0] WE0_buf;
  wire [3:0] float_buf_en;
  wire [3:0] lo;
  CLKBUF_4 \A0BUF[0]  (
    .A(A0[0]),
    .X(A0_buf[0])
  );
  CLKBUF_4 \A0BUF[1]  (
    .A(A0[1]),
    .X(A0_buf[1])
  );
  CLKBUF_4 \A0BUF[2]  (
    .A(A0[2]),
    .X(A0_buf[2])
  );
  CLKBUF_4 \A0BUF[3]  (
    .A(A0[3]),
    .X(A0_buf[3])
  );
  EBUFN_2 \BYTE[0].FLOATBUF0[0]  (
    .A(lo[0]),
    .TE_B(float_buf_en[0]),
    .Z(Do0_pre[0])
  );
  EBUFN_2 \BYTE[0].FLOATBUF0[1]  (
    .A(lo[0]),
    .TE_B(float_buf_en[0]),
    .Z(Do0_pre[1])
  );
  EBUFN_2 \BYTE[0].FLOATBUF0[2]  (
    .A(lo[0]),
    .TE_B(float_buf_en[0]),
    .Z(Do0_pre[2])
  );
  EBUFN_2 \BYTE[0].FLOATBUF0[3]  (
    .A(lo[0]),
    .TE_B(float_buf_en[0]),
    .Z(Do0_pre[3])
  );
  EBUFN_2 \BYTE[0].FLOATBUF0[4]  (
    .A(lo[0]),
    .TE_B(float_buf_en[0]),
    .Z(Do0_pre[4])
  );
  EBUFN_2 \BYTE[0].FLOATBUF0[5]  (
    .A(lo[0]),
    .TE_B(float_buf_en[0]),
    .Z(Do0_pre[5])
  );
  EBUFN_2 \BYTE[0].FLOATBUF0[6]  (
    .A(lo[0]),
    .TE_B(float_buf_en[0]),
    .Z(Do0_pre[6])
  );
  EBUFN_2 \BYTE[0].FLOATBUF0[7]  (
    .A(lo[0]),
    .TE_B(float_buf_en[0]),
    .Z(Do0_pre[7])
  );
  EBUFN_2 \BYTE[1].FLOATBUF0[10]  (
    .A(lo[1]),
    .TE_B(float_buf_en[1]),
    .Z(Do0_pre[10])
  );
  EBUFN_2 \BYTE[1].FLOATBUF0[11]  (
    .A(lo[1]),
    .TE_B(float_buf_en[1]),
    .Z(Do0_pre[11])
  );
  EBUFN_2 \BYTE[1].FLOATBUF0[12]  (
    .A(lo[1]),
    .TE_B(float_buf_en[1]),
    .Z(Do0_pre[12])
  );
  EBUFN_2 \BYTE[1].FLOATBUF0[13]  (
    .A(lo[1]),
    .TE_B(float_buf_en[1]),
    .Z(Do0_pre[13])
  );
  EBUFN_2 \BYTE[1].FLOATBUF0[14]  (
    .A(lo[1]),
    .TE_B(float_buf_en[1]),
    .Z(Do0_pre[14])
  );
  EBUFN_2 \BYTE[1].FLOATBUF0[15]  (
    .A(lo[1]),
    .TE_B(float_buf_en[1]),
    .Z(Do0_pre[15])
  );
  EBUFN_2 \BYTE[1].FLOATBUF0[8]  (
    .A(lo[1]),
    .TE_B(float_buf_en[1]),
    .Z(Do0_pre[8])
  );
  EBUFN_2 \BYTE[1].FLOATBUF0[9]  (
    .A(lo[1]),
    .TE_B(float_buf_en[1]),
    .Z(Do0_pre[9])
  );
  EBUFN_2 \BYTE[2].FLOATBUF0[16]  (
    .A(lo[2]),
    .TE_B(float_buf_en[2]),
    .Z(Do0_pre[16])
  );
  EBUFN_2 \BYTE[2].FLOATBUF0[17]  (
    .A(lo[2]),
    .TE_B(float_buf_en[2]),
    .Z(Do0_pre[17])
  );
  EBUFN_2 \BYTE[2].FLOATBUF0[18]  (
    .A(lo[2]),
    .TE_B(float_buf_en[2]),
    .Z(Do0_pre[18])
  );
  EBUFN_2 \BYTE[2].FLOATBUF0[19]  (
    .A(lo[2]),
    .TE_B(float_buf_en[2]),
    .Z(Do0_pre[19])
  );
  EBUFN_2 \BYTE[2].FLOATBUF0[20]  (
    .A(lo[2]),
    .TE_B(float_buf_en[2]),
    .Z(Do0_pre[20])
  );
  EBUFN_2 \BYTE[2].FLOATBUF0[21]  (
    .A(lo[2]),
    .TE_B(float_buf_en[2]),
    .Z(Do0_pre[21])
  );
  EBUFN_2 \BYTE[2].FLOATBUF0[22]  (
    .A(lo[2]),
    .TE_B(float_buf_en[2]),
    .Z(Do0_pre[22])
  );
  EBUFN_2 \BYTE[2].FLOATBUF0[23]  (
    .A(lo[2]),
    .TE_B(float_buf_en[2]),
    .Z(Do0_pre[23])
  );
  EBUFN_2 \BYTE[3].FLOATBUF0[24]  (
    .A(lo[3]),
    .TE_B(float_buf_en[3]),
    .Z(Do0_pre[24])
  );
  EBUFN_2 \BYTE[3].FLOATBUF0[25]  (
    .A(lo[3]),
    .TE_B(float_buf_en[3]),
    .Z(Do0_pre[25])
  );
  EBUFN_2 \BYTE[3].FLOATBUF0[26]  (
    .A(lo[3]),
    .TE_B(float_buf_en[3]),
    .Z(Do0_pre[26])
  );
  EBUFN_2 \BYTE[3].FLOATBUF0[27]  (
    .A(lo[3]),
    .TE_B(float_buf_en[3]),
    .Z(Do0_pre[27])
  );
  EBUFN_2 \BYTE[3].FLOATBUF0[28]  (
    .A(lo[3]),
    .TE_B(float_buf_en[3]),
    .Z(Do0_pre[28])
  );
  EBUFN_2 \BYTE[3].FLOATBUF0[29]  (
    .A(lo[3]),
    .TE_B(float_buf_en[3]),
    .Z(Do0_pre[29])
  );
  EBUFN_2 \BYTE[3].FLOATBUF0[30]  (
    .A(lo[3]),
    .TE_B(float_buf_en[3]),
    .Z(Do0_pre[30])
  );
  EBUFN_2 \BYTE[3].FLOATBUF0[31]  (
    .A(lo[3]),
    .TE_B(float_buf_en[3]),
    .Z(Do0_pre[31])
  );
  CLKBUF_4 CLKBUF (
    .A(CLK),
    .X(CLK_buf)
  );
  DEC1x2 DEC0 (
    .A(A0_buf[3]),
    .EN(EN0_buf),
    .SEL(SEL0)
  );
  CLKBUF_4 \DIBUF[0]  (
    .A(Di0[0]),
    .X(Di0_buf[0])
  );
  CLKBUF_4 \DIBUF[10]  (
    .A(Di0[10]),
    .X(Di0_buf[10])
  );
  CLKBUF_4 \DIBUF[11]  (
    .A(Di0[11]),
    .X(Di0_buf[11])
  );
  CLKBUF_4 \DIBUF[12]  (
    .A(Di0[12]),
    .X(Di0_buf[12])
  );
  CLKBUF_4 \DIBUF[13]  (
    .A(Di0[13]),
    .X(Di0_buf[13])
  );
  CLKBUF_4 \DIBUF[14]  (
    .A(Di0[14]),
    .X(Di0_buf[14])
  );
  CLKBUF_4 \DIBUF[15]  (
    .A(Di0[15]),
    .X(Di0_buf[15])
  );
  CLKBUF_4 \DIBUF[16]  (
    .A(Di0[16]),
    .X(Di0_buf[16])
  );
  CLKBUF_4 \DIBUF[17]  (
    .A(Di0[17]),
    .X(Di0_buf[17])
  );
  CLKBUF_4 \DIBUF[18]  (
    .A(Di0[18]),
    .X(Di0_buf[18])
  );
  CLKBUF_4 \DIBUF[19]  (
    .A(Di0[19]),
    .X(Di0_buf[19])
  );
  CLKBUF_4 \DIBUF[1]  (
    .A(Di0[1]),
    .X(Di0_buf[1])
  );
  CLKBUF_4 \DIBUF[20]  (
    .A(Di0[20]),
    .X(Di0_buf[20])
  );
  CLKBUF_4 \DIBUF[21]  (
    .A(Di0[21]),
    .X(Di0_buf[21])
  );
  CLKBUF_4 \DIBUF[22]  (
    .A(Di0[22]),
    .X(Di0_buf[22])
  );
  CLKBUF_4 \DIBUF[23]  (
    .A(Di0[23]),
    .X(Di0_buf[23])
  );
  CLKBUF_4 \DIBUF[24]  (
    .A(Di0[24]),
    .X(Di0_buf[24])
  );
  CLKBUF_4 \DIBUF[25]  (
    .A(Di0[25]),
    .X(Di0_buf[25])
  );
  CLKBUF_4 \DIBUF[26]  (
    .A(Di0[26]),
    .X(Di0_buf[26])
  );
  CLKBUF_4 \DIBUF[27]  (
    .A(Di0[27]),
    .X(Di0_buf[27])
  );
  CLKBUF_4 \DIBUF[28]  (
    .A(Di0[28]),
    .X(Di0_buf[28])
  );
  CLKBUF_4 \DIBUF[29]  (
    .A(Di0[29]),
    .X(Di0_buf[29])
  );
  CLKBUF_4 \DIBUF[2]  (
    .A(Di0[2]),
    .X(Di0_buf[2])
  );
  CLKBUF_4 \DIBUF[30]  (
    .A(Di0[30]),
    .X(Di0_buf[30])
  );
  CLKBUF_4 \DIBUF[31]  (
    .A(Di0[31]),
    .X(Di0_buf[31])
  );
  CLKBUF_4 \DIBUF[3]  (
    .A(Di0[3]),
    .X(Di0_buf[3])
  );
  CLKBUF_4 \DIBUF[4]  (
    .A(Di0[4]),
    .X(Di0_buf[4])
  );
  CLKBUF_4 \DIBUF[5]  (
    .A(Di0[5]),
    .X(Di0_buf[5])
  );
  CLKBUF_4 \DIBUF[6]  (
    .A(Di0[6]),
    .X(Di0_buf[6])
  );
  CLKBUF_4 \DIBUF[7]  (
    .A(Di0[7]),
    .X(Di0_buf[7])
  );
  CLKBUF_4 \DIBUF[8]  (
    .A(Di0[8]),
    .X(Di0_buf[8])
  );
  CLKBUF_4 \DIBUF[9]  (
    .A(Di0[9]),
    .X(Di0_buf[9])
  );
  \$paramod\OUTREG\WIDTH=32'00000000000000000000000000100000  Do0_REG (
    .CLK(CLK_buf),
    .Di(Do0_pre),
    .Do(Do0),
    .EN(EN0_buf)
  );
  CLKBUF_4 EN0BUF (
    .A(EN0),
    .X(EN0_buf)
  );
  CLKBUF_2 \FBUFENBUF0[0]  (
    .A(EN0),
    .X(float_buf_en[0])
  );
  CLKBUF_2 \FBUFENBUF0[1]  (
    .A(EN0),
    .X(float_buf_en[1])
  );
  CLKBUF_2 \FBUFENBUF0[2]  (
    .A(EN0),
    .X(float_buf_en[2])
  );
  CLKBUF_2 \FBUFENBUF0[3]  (
    .A(EN0),
    .X(float_buf_en[3])
  );
  \$paramod$0a04d2ca855f7a52b7b0f8269f16a7f2c6677e46\RAM8  \SLICE[0].RAM8  (
    .A0(A0_buf[2:0]),
    .CLK(CLK_buf),
    .Di0(Di0_buf),
    .Do0(Do0_pre),
    .EN0(SEL0[0]),
    .WE0(WE0_buf)
  );
  \$paramod$0a04d2ca855f7a52b7b0f8269f16a7f2c6677e46\RAM8  \SLICE[1].RAM8  (
    .A0(A0_buf[2:0]),
    .CLK(CLK_buf),
    .Di0(Di0_buf),
    .Do0(Do0_pre),
    .EN0(SEL0[1]),
    .WE0(WE0_buf)
  );
  CONB \TIE0[0]  (
    .LO(lo[0])
  );
  CONB \TIE0[1]  (
    .LO(lo[1])
  );
  CONB \TIE0[2]  (
    .LO(lo[2])
  );
  CONB \TIE0[3]  (
    .LO(lo[3])
  );
  CLKBUF_2 \WEBUF[0]  (
    .A(WE0[0]),
    .X(WE0_buf[0])
  );
  CLKBUF_2 \WEBUF[1]  (
    .A(WE0[1]),
    .X(WE0_buf[1])
  );
  CLKBUF_2 \WEBUF[2]  (
    .A(WE0[2]),
    .X(WE0_buf[2])
  );
  CLKBUF_2 \WEBUF[3]  (
    .A(WE0[3]),
    .X(WE0_buf[3])
  );
endmodule

module \$paramod$0a04d2ca855f7a52b7b0f8269f16a7f2c6677e46\RAM8 (CLK, WE0, EN0, A0, Di0, Do0);
  input CLK;
  wire CLK;
  input [3:0] WE0;
  wire [3:0] WE0;
  input EN0;
  wire EN0;
  input [2:0] A0;
  wire [2:0] A0;
  input [31:0] Di0;
  wire [31:0] Di0;
  output [31:0] Do0;
  wire [31:0] Do0;
  wire CLK_buf;
  wire [7:0] SEL0;
  wire [3:0] WE0_buf;
  CLKBUF_2 CLKBUF (
    .A(CLK),
    .X(CLK_buf)
  );
  DEC3x8 DEC0 (
    .A(A0),
    .EN(EN0),
    .SEL(SEL0)
  );
  CLKBUF_2 \WEBUF[0]  (
    .A(WE0[0]),
    .X(WE0_buf[0])
  );
  CLKBUF_2 \WEBUF[1]  (
    .A(WE0[1]),
    .X(WE0_buf[1])
  );
  CLKBUF_2 \WEBUF[2]  (
    .A(WE0[2]),
    .X(WE0_buf[2])
  );
  CLKBUF_2 \WEBUF[3]  (
    .A(WE0[3]),
    .X(WE0_buf[3])
  );
  \$paramod$0a04d2ca855f7a52b7b0f8269f16a7f2c6677e46\WORD  \WORD[0].W  (
    .CLK(CLK_buf),
    .Di0(Di0),
    .Do0(Do0),
    .SEL0(SEL0[0]),
    .WE0(WE0_buf)
  );
  \$paramod$0a04d2ca855f7a52b7b0f8269f16a7f2c6677e46\WORD  \WORD[1].W  (
    .CLK(CLK_buf),
    .Di0(Di0),
    .Do0(Do0),
    .SEL0(SEL0[1]),
    .WE0(WE0_buf)
  );
  \$paramod$0a04d2ca855f7a52b7b0f8269f16a7f2c6677e46\WORD  \WORD[2].W  (
    .CLK(CLK_buf),
    .Di0(Di0),
    .Do0(Do0),
    .SEL0(SEL0[2]),
    .WE0(WE0_buf)
  );
  \$paramod$0a04d2ca855f7a52b7b0f8269f16a7f2c6677e46\WORD  \WORD[3].W  (
    .CLK(CLK_buf),
    .Di0(Di0),
    .Do0(Do0),
    .SEL0(SEL0[3]),
    .WE0(WE0_buf)
  );
  \$paramod$0a04d2ca855f7a52b7b0f8269f16a7f2c6677e46\WORD  \WORD[4].W  (
    .CLK(CLK_buf),
    .Di0(Di0),
    .Do0(Do0),
    .SEL0(SEL0[4]),
    .WE0(WE0_buf)
  );
  \$paramod$0a04d2ca855f7a52b7b0f8269f16a7f2c6677e46\WORD  \WORD[5].W  (
    .CLK(CLK_buf),
    .Di0(Di0),
    .Do0(Do0),
    .SEL0(SEL0[5]),
    .WE0(WE0_buf)
  );
  \$paramod$0a04d2ca855f7a52b7b0f8269f16a7f2c6677e46\WORD  \WORD[6].W  (
    .CLK(CLK_buf),
    .Di0(Di0),
    .Do0(Do0),
    .SEL0(SEL0[6]),
    .WE0(WE0_buf)
  );
  \$paramod$0a04d2ca855f7a52b7b0f8269f16a7f2c6677e46\WORD  \WORD[7].W  (
    .CLK(CLK_buf),
    .Di0(Di0),
    .Do0(Do0),
    .SEL0(SEL0[7]),
    .WE0(WE0_buf)
  );
endmodule

module \$paramod$0a04d2ca855f7a52b7b0f8269f16a7f2c6677e46\WORD (CLK, WE0, SEL0, Di0, Do0);
  input CLK;
  wire CLK;
  input [3:0] WE0;
  wire [3:0] WE0;
  input SEL0;
  wire SEL0;
  input [31:0] Di0;
  wire [31:0] Di0;
  output [31:0] Do0;
  wire [31:0] Do0;
  wire CLK_buf;
  wire SEL0_buf;
  \$paramod\BYTE\USE_LATCH=32'00000000000000000000000000000001  \BYTE[0].B  (
    .CLK(CLK_buf),
    .Di0(Di0[7:0]),
    .Do0(Do0[7:0]),
    .SEL0(SEL0_buf),
    .WE0(WE0[0])
  );
  \$paramod\BYTE\USE_LATCH=32'00000000000000000000000000000001  \BYTE[1].B  (
    .CLK(CLK_buf),
    .Di0(Di0[15:8]),
    .Do0(Do0[15:8]),
    .SEL0(SEL0_buf),
    .WE0(WE0[1])
  );
  \$paramod\BYTE\USE_LATCH=32'00000000000000000000000000000001  \BYTE[2].B  (
    .CLK(CLK_buf),
    .Di0(Di0[23:16]),
    .Do0(Do0[23:16]),
    .SEL0(SEL0_buf),
    .WE0(WE0[2])
  );
  \$paramod\BYTE\USE_LATCH=32'00000000000000000000000000000001  \BYTE[3].B  (
    .CLK(CLK_buf),
    .Di0(Di0[31:24]),
    .Do0(Do0[31:24]),
    .SEL0(SEL0_buf),
    .WE0(WE0[3])
  );
  sky130_fd_sc_hd__clkbuf_4 CLKBUF (
    .A(CLK),
    .X(CLK_buf)
  );
  sky130_fd_sc_hd__clkbuf_4 SEL0BUF (
    .A(SEL0),
    .X(SEL0_buf)
  );
endmodule

module \$paramod\BYTE\USE_LATCH=32'00000000000000000000000000000001 (CLK, WE0, SEL0, Di0, Do0);
  input CLK;
  wire CLK;
  input WE0;
  wire WE0;
  input SEL0;
  wire SEL0;
  input [7:0] Di0;
  wire [7:0] Di0;
  output [7:0] Do0;
  wire [7:0] Do0;
  wire CLK_B;
  wire GCLK;
  wire [7:0] Q_WIRE;
  wire SEL0_B;
  wire WE0_WIRE;
  sky130_fd_sc_hd__ebufn_2 \BIT[0].OBUF0  (
    .A(Q_WIRE[0]),
    .TE_B(SEL0_B),
    .Z(Do0[0])
  );
  sky130_fd_sc_hd__dlxtp_1 \BIT[0].genblk1.STORAGE  (
    .D(Di0[0]),
    .GATE(GCLK),
    .Q(Q_WIRE[0])
  );
  sky130_fd_sc_hd__ebufn_2 \BIT[1].OBUF0  (
    .A(Q_WIRE[1]),
    .TE_B(SEL0_B),
    .Z(Do0[1])
  );
  sky130_fd_sc_hd__dlxtp_1 \BIT[1].genblk1.STORAGE  (
    .D(Di0[1]),
    .GATE(GCLK),
    .Q(Q_WIRE[1])
  );
  sky130_fd_sc_hd__ebufn_2 \BIT[2].OBUF0  (
    .A(Q_WIRE[2]),
    .TE_B(SEL0_B),
    .Z(Do0[2])
  );
  sky130_fd_sc_hd__dlxtp_1 \BIT[2].genblk1.STORAGE  (
    .D(Di0[2]),
    .GATE(GCLK),
    .Q(Q_WIRE[2])
  );
  sky130_fd_sc_hd__ebufn_2 \BIT[3].OBUF0  (
    .A(Q_WIRE[3]),
    .TE_B(SEL0_B),
    .Z(Do0[3])
  );
  sky130_fd_sc_hd__dlxtp_1 \BIT[3].genblk1.STORAGE  (
    .D(Di0[3]),
    .GATE(GCLK),
    .Q(Q_WIRE[3])
  );
  sky130_fd_sc_hd__ebufn_2 \BIT[4].OBUF0  (
    .A(Q_WIRE[4]),
    .TE_B(SEL0_B),
    .Z(Do0[4])
  );
  sky130_fd_sc_hd__dlxtp_1 \BIT[4].genblk1.STORAGE  (
    .D(Di0[4]),
    .GATE(GCLK),
    .Q(Q_WIRE[4])
  );
  sky130_fd_sc_hd__ebufn_2 \BIT[5].OBUF0  (
    .A(Q_WIRE[5]),
    .TE_B(SEL0_B),
    .Z(Do0[5])
  );
  sky130_fd_sc_hd__dlxtp_1 \BIT[5].genblk1.STORAGE  (
    .D(Di0[5]),
    .GATE(GCLK),
    .Q(Q_WIRE[5])
  );
  sky130_fd_sc_hd__ebufn_2 \BIT[6].OBUF0  (
    .A(Q_WIRE[6]),
    .TE_B(SEL0_B),
    .Z(Do0[6])
  );
  sky130_fd_sc_hd__dlxtp_1 \BIT[6].genblk1.STORAGE  (
    .D(Di0[6]),
    .GATE(GCLK),
    .Q(Q_WIRE[6])
  );
  sky130_fd_sc_hd__ebufn_2 \BIT[7].OBUF0  (
    .A(Q_WIRE[7]),
    .TE_B(SEL0_B),
    .Z(Do0[7])
  );
  sky130_fd_sc_hd__dlxtp_1 \BIT[7].genblk1.STORAGE  (
    .D(Di0[7]),
    .GATE(GCLK),
    .Q(Q_WIRE[7])
  );
  sky130_fd_sc_hd__and2_1 CGAND (
    .A(SEL0),
    .B(WE0),
    .X(WE0_WIRE)
  );
  sky130_fd_sc_hd__inv_1 SEL0INV (
    .A(SEL0),
    .Y(SEL0_B)
  );
  sky130_fd_sc_hd__dlclkp_1 \genblk1.CG  (
    .CLK(CLK_B),
    .GATE(WE0_WIRE),
    .GCLK(GCLK)
  );
  sky130_fd_sc_hd__inv_1 \genblk1.CLKINV  (
    .A(CLK),
    .Y(CLK_B)
  );
endmodule

module \$paramod\MUX2x1\WIDTH=32'00000000000000000000000000100000 (A0, A1, S, X);
  input [31:0] A0;
  wire [31:0] A0;
  input [31:0] A1;
  wire [31:0] A1;
  input S;
  wire S;
  output [31:0] X;
  wire [31:0] X;
  wire [3:0] SEL;
  sky130_fd_sc_hd__mux2_1 \M[0].MUX[0]  (
    .A0(A0[0]),
    .A1(A1[0]),
    .S(SEL[0]),
    .X(X[0])
  );
  sky130_fd_sc_hd__mux2_1 \M[0].MUX[1]  (
    .A0(A0[1]),
    .A1(A1[1]),
    .S(SEL[0]),
    .X(X[1])
  );
  sky130_fd_sc_hd__mux2_1 \M[0].MUX[2]  (
    .A0(A0[2]),
    .A1(A1[2]),
    .S(SEL[0]),
    .X(X[2])
  );
  sky130_fd_sc_hd__mux2_1 \M[0].MUX[3]  (
    .A0(A0[3]),
    .A1(A1[3]),
    .S(SEL[0]),
    .X(X[3])
  );
  sky130_fd_sc_hd__mux2_1 \M[0].MUX[4]  (
    .A0(A0[4]),
    .A1(A1[4]),
    .S(SEL[0]),
    .X(X[4])
  );
  sky130_fd_sc_hd__mux2_1 \M[0].MUX[5]  (
    .A0(A0[5]),
    .A1(A1[5]),
    .S(SEL[0]),
    .X(X[5])
  );
  sky130_fd_sc_hd__mux2_1 \M[0].MUX[6]  (
    .A0(A0[6]),
    .A1(A1[6]),
    .S(SEL[0]),
    .X(X[6])
  );
  sky130_fd_sc_hd__mux2_1 \M[0].MUX[7]  (
    .A0(A0[7]),
    .A1(A1[7]),
    .S(SEL[0]),
    .X(X[7])
  );
  sky130_fd_sc_hd__mux2_1 \M[1].MUX[0]  (
    .A0(A0[8]),
    .A1(A1[8]),
    .S(SEL[1]),
    .X(X[8])
  );
  sky130_fd_sc_hd__mux2_1 \M[1].MUX[1]  (
    .A0(A0[9]),
    .A1(A1[9]),
    .S(SEL[1]),
    .X(X[9])
  );
  sky130_fd_sc_hd__mux2_1 \M[1].MUX[2]  (
    .A0(A0[10]),
    .A1(A1[10]),
    .S(SEL[1]),
    .X(X[10])
  );
  sky130_fd_sc_hd__mux2_1 \M[1].MUX[3]  (
    .A0(A0[11]),
    .A1(A1[11]),
    .S(SEL[1]),
    .X(X[11])
  );
  sky130_fd_sc_hd__mux2_1 \M[1].MUX[4]  (
    .A0(A0[12]),
    .A1(A1[12]),
    .S(SEL[1]),
    .X(X[12])
  );
  sky130_fd_sc_hd__mux2_1 \M[1].MUX[5]  (
    .A0(A0[13]),
    .A1(A1[13]),
    .S(SEL[1]),
    .X(X[13])
  );
  sky130_fd_sc_hd__mux2_1 \M[1].MUX[6]  (
    .A0(A0[14]),
    .A1(A1[14]),
    .S(SEL[1]),
    .X(X[14])
  );
  sky130_fd_sc_hd__mux2_1 \M[1].MUX[7]  (
    .A0(A0[15]),
    .A1(A1[15]),
    .S(SEL[1]),
    .X(X[15])
  );
  sky130_fd_sc_hd__mux2_1 \M[2].MUX[0]  (
    .A0(A0[16]),
    .A1(A1[16]),
    .S(SEL[2]),
    .X(X[16])
  );
  sky130_fd_sc_hd__mux2_1 \M[2].MUX[1]  (
    .A0(A0[17]),
    .A1(A1[17]),
    .S(SEL[2]),
    .X(X[17])
  );
  sky130_fd_sc_hd__mux2_1 \M[2].MUX[2]  (
    .A0(A0[18]),
    .A1(A1[18]),
    .S(SEL[2]),
    .X(X[18])
  );
  sky130_fd_sc_hd__mux2_1 \M[2].MUX[3]  (
    .A0(A0[19]),
    .A1(A1[19]),
    .S(SEL[2]),
    .X(X[19])
  );
  sky130_fd_sc_hd__mux2_1 \M[2].MUX[4]  (
    .A0(A0[20]),
    .A1(A1[20]),
    .S(SEL[2]),
    .X(X[20])
  );
  sky130_fd_sc_hd__mux2_1 \M[2].MUX[5]  (
    .A0(A0[21]),
    .A1(A1[21]),
    .S(SEL[2]),
    .X(X[21])
  );
  sky130_fd_sc_hd__mux2_1 \M[2].MUX[6]  (
    .A0(A0[22]),
    .A1(A1[22]),
    .S(SEL[2]),
    .X(X[22])
  );
  sky130_fd_sc_hd__mux2_1 \M[2].MUX[7]  (
    .A0(A0[23]),
    .A1(A1[23]),
    .S(SEL[2]),
    .X(X[23])
  );
  sky130_fd_sc_hd__mux2_1 \M[3].MUX[0]  (
    .A0(A0[24]),
    .A1(A1[24]),
    .S(SEL[3]),
    .X(X[24])
  );
  sky130_fd_sc_hd__mux2_1 \M[3].MUX[1]  (
    .A0(A0[25]),
    .A1(A1[25]),
    .S(SEL[3]),
    .X(X[25])
  );
  sky130_fd_sc_hd__mux2_1 \M[3].MUX[2]  (
    .A0(A0[26]),
    .A1(A1[26]),
    .S(SEL[3]),
    .X(X[26])
  );
  sky130_fd_sc_hd__mux2_1 \M[3].MUX[3]  (
    .A0(A0[27]),
    .A1(A1[27]),
    .S(SEL[3]),
    .X(X[27])
  );
  sky130_fd_sc_hd__mux2_1 \M[3].MUX[4]  (
    .A0(A0[28]),
    .A1(A1[28]),
    .S(SEL[3]),
    .X(X[28])
  );
  sky130_fd_sc_hd__mux2_1 \M[3].MUX[5]  (
    .A0(A0[29]),
    .A1(A1[29]),
    .S(SEL[3]),
    .X(X[29])
  );
  sky130_fd_sc_hd__mux2_1 \M[3].MUX[6]  (
    .A0(A0[30]),
    .A1(A1[30]),
    .S(SEL[3]),
    .X(X[30])
  );
  sky130_fd_sc_hd__mux2_1 \M[3].MUX[7]  (
    .A0(A0[31]),
    .A1(A1[31]),
    .S(SEL[3]),
    .X(X[31])
  );
  sky130_fd_sc_hd__clkbuf_2 \SEL0BUF[0]  (
    .A(S),
    .X(SEL[0])
  );
  sky130_fd_sc_hd__clkbuf_2 \SEL0BUF[1]  (
    .A(S),
    .X(SEL[1])
  );
  sky130_fd_sc_hd__clkbuf_2 \SEL0BUF[2]  (
    .A(S),
    .X(SEL[2])
  );
  sky130_fd_sc_hd__clkbuf_2 \SEL0BUF[3]  (
    .A(S),
    .X(SEL[3])
  );
endmodule

module \$paramod\OUTREG\WIDTH=32'00000000000000000000000000100000 (CLK, EN, Di, Do);
  input CLK;
  wire CLK;
  input EN;
  wire EN;
  input [31:0] Di;
  wire [31:0] Di;
  output [31:0] Do;
  wire [31:0] Do;
  wire [3:0] CLKBUF;
  wire GCLK;
  sky130_fd_sc_hd__dlclkp_1 CG (
    .CLK(CLK),
    .GATE(EN),
    .GCLK(GCLK)
  );
  sky130_fd_sc_hd__clkbuf_4 \Do_CLKBUF[0]  (
    .A(GCLK),
    .X(CLKBUF[0])
  );
  sky130_fd_sc_hd__clkbuf_4 \Do_CLKBUF[1]  (
    .A(GCLK),
    .X(CLKBUF[1])
  );
  sky130_fd_sc_hd__clkbuf_4 \Do_CLKBUF[2]  (
    .A(GCLK),
    .X(CLKBUF[2])
  );
  sky130_fd_sc_hd__clkbuf_4 \Do_CLKBUF[3]  (
    .A(GCLK),
    .X(CLKBUF[3])
  );
  sky130_fd_sc_hd__dfxtp_1 \OUTREG_BYTE[0].Do_FF[0]  (
    .CLK(CLKBUF[0]),
    .D(Di[0]),
    .Q(Do[0])
  );
  sky130_fd_sc_hd__dfxtp_1 \OUTREG_BYTE[0].Do_FF[1]  (
    .CLK(CLKBUF[0]),
    .D(Di[1]),
    .Q(Do[1])
  );
  sky130_fd_sc_hd__dfxtp_1 \OUTREG_BYTE[0].Do_FF[2]  (
    .CLK(CLKBUF[0]),
    .D(Di[2]),
    .Q(Do[2])
  );
  sky130_fd_sc_hd__dfxtp_1 \OUTREG_BYTE[0].Do_FF[3]  (
    .CLK(CLKBUF[0]),
    .D(Di[3]),
    .Q(Do[3])
  );
  sky130_fd_sc_hd__dfxtp_1 \OUTREG_BYTE[0].Do_FF[4]  (
    .CLK(CLKBUF[0]),
    .D(Di[4]),
    .Q(Do[4])
  );
  sky130_fd_sc_hd__dfxtp_1 \OUTREG_BYTE[0].Do_FF[5]  (
    .CLK(CLKBUF[0]),
    .D(Di[5]),
    .Q(Do[5])
  );
  sky130_fd_sc_hd__dfxtp_1 \OUTREG_BYTE[0].Do_FF[6]  (
    .CLK(CLKBUF[0]),
    .D(Di[6]),
    .Q(Do[6])
  );
  sky130_fd_sc_hd__dfxtp_1 \OUTREG_BYTE[0].Do_FF[7]  (
    .CLK(CLKBUF[0]),
    .D(Di[7]),
    .Q(Do[7])
  );
  sky130_fd_sc_hd__dfxtp_1 \OUTREG_BYTE[1].Do_FF[0]  (
    .CLK(CLKBUF[1]),
    .D(Di[8]),
    .Q(Do[8])
  );
  sky130_fd_sc_hd__dfxtp_1 \OUTREG_BYTE[1].Do_FF[1]  (
    .CLK(CLKBUF[1]),
    .D(Di[9]),
    .Q(Do[9])
  );
  sky130_fd_sc_hd__dfxtp_1 \OUTREG_BYTE[1].Do_FF[2]  (
    .CLK(CLKBUF[1]),
    .D(Di[10]),
    .Q(Do[10])
  );
  sky130_fd_sc_hd__dfxtp_1 \OUTREG_BYTE[1].Do_FF[3]  (
    .CLK(CLKBUF[1]),
    .D(Di[11]),
    .Q(Do[11])
  );
  sky130_fd_sc_hd__dfxtp_1 \OUTREG_BYTE[1].Do_FF[4]  (
    .CLK(CLKBUF[1]),
    .D(Di[12]),
    .Q(Do[12])
  );
  sky130_fd_sc_hd__dfxtp_1 \OUTREG_BYTE[1].Do_FF[5]  (
    .CLK(CLKBUF[1]),
    .D(Di[13]),
    .Q(Do[13])
  );
  sky130_fd_sc_hd__dfxtp_1 \OUTREG_BYTE[1].Do_FF[6]  (
    .CLK(CLKBUF[1]),
    .D(Di[14]),
    .Q(Do[14])
  );
  sky130_fd_sc_hd__dfxtp_1 \OUTREG_BYTE[1].Do_FF[7]  (
    .CLK(CLKBUF[1]),
    .D(Di[15]),
    .Q(Do[15])
  );
  sky130_fd_sc_hd__dfxtp_1 \OUTREG_BYTE[2].Do_FF[0]  (
    .CLK(CLKBUF[2]),
    .D(Di[16]),
    .Q(Do[16])
  );
  sky130_fd_sc_hd__dfxtp_1 \OUTREG_BYTE[2].Do_FF[1]  (
    .CLK(CLKBUF[2]),
    .D(Di[17]),
    .Q(Do[17])
  );
  sky130_fd_sc_hd__dfxtp_1 \OUTREG_BYTE[2].Do_FF[2]  (
    .CLK(CLKBUF[2]),
    .D(Di[18]),
    .Q(Do[18])
  );
  sky130_fd_sc_hd__dfxtp_1 \OUTREG_BYTE[2].Do_FF[3]  (
    .CLK(CLKBUF[2]),
    .D(Di[19]),
    .Q(Do[19])
  );
  sky130_fd_sc_hd__dfxtp_1 \OUTREG_BYTE[2].Do_FF[4]  (
    .CLK(CLKBUF[2]),
    .D(Di[20]),
    .Q(Do[20])
  );
  sky130_fd_sc_hd__dfxtp_1 \OUTREG_BYTE[2].Do_FF[5]  (
    .CLK(CLKBUF[2]),
    .D(Di[21]),
    .Q(Do[21])
  );
  sky130_fd_sc_hd__dfxtp_1 \OUTREG_BYTE[2].Do_FF[6]  (
    .CLK(CLKBUF[2]),
    .D(Di[22]),
    .Q(Do[22])
  );
  sky130_fd_sc_hd__dfxtp_1 \OUTREG_BYTE[2].Do_FF[7]  (
    .CLK(CLKBUF[2]),
    .D(Di[23]),
    .Q(Do[23])
  );
  sky130_fd_sc_hd__dfxtp_1 \OUTREG_BYTE[3].Do_FF[0]  (
    .CLK(CLKBUF[3]),
    .D(Di[24]),
    .Q(Do[24])
  );
  sky130_fd_sc_hd__dfxtp_1 \OUTREG_BYTE[3].Do_FF[1]  (
    .CLK(CLKBUF[3]),
    .D(Di[25]),
    .Q(Do[25])
  );
  sky130_fd_sc_hd__dfxtp_1 \OUTREG_BYTE[3].Do_FF[2]  (
    .CLK(CLKBUF[3]),
    .D(Di[26]),
    .Q(Do[26])
  );
  sky130_fd_sc_hd__dfxtp_1 \OUTREG_BYTE[3].Do_FF[3]  (
    .CLK(CLKBUF[3]),
    .D(Di[27]),
    .Q(Do[27])
  );
  sky130_fd_sc_hd__dfxtp_1 \OUTREG_BYTE[3].Do_FF[4]  (
    .CLK(CLKBUF[3]),
    .D(Di[28]),
    .Q(Do[28])
  );
  sky130_fd_sc_hd__dfxtp_1 \OUTREG_BYTE[3].Do_FF[5]  (
    .CLK(CLKBUF[3]),
    .D(Di[29]),
    .Q(Do[29])
  );
  sky130_fd_sc_hd__dfxtp_1 \OUTREG_BYTE[3].Do_FF[6]  (
    .CLK(CLKBUF[3]),
    .D(Di[30]),
    .Q(Do[30])
  );
  sky130_fd_sc_hd__dfxtp_1 \OUTREG_BYTE[3].Do_FF[7]  (
    .CLK(CLKBUF[3]),
    .D(Di[31]),
    .Q(Do[31])
  );
endmodule

module CLKBUF_16(A, X);
  input A;
  wire A;
  output X;
  wire X;
  sky130_fd_sc_hd__clkbuf_16 __cell__ (
    .A(A),
    .X(X)
  );
endmodule

module CLKBUF_2(A, X);
  input A;
  wire A;
  output X;
  wire X;
  sky130_fd_sc_hd__clkbuf_2 __cell__ (
    .A(A),
    .X(X)
  );
endmodule

module CLKBUF_4(A, X);
  input A;
  wire A;
  output X;
  wire X;
  sky130_fd_sc_hd__clkbuf_4 __cell__ (
    .A(A),
    .X(X)
  );
endmodule

module CONB(HI, LO);
  output HI;
  wire HI;
  output LO;
  wire LO;
  sky130_fd_sc_hd__conb_1 __cell__ (
    .LO(LO)
  );
endmodule

module DEC1x2(EN, A, SEL);
  input EN;
  wire EN;
  input A;
  wire A;
  output [1:0] SEL;
  wire [1:0] SEL;
  sky130_fd_sc_hd__and2b_4 AND0 (
    .A_N(A),
    .B(EN),
    .X(SEL[0])
  );
  sky130_fd_sc_hd__and2_4 AND1 (
    .A(A),
    .B(EN),
    .X(SEL[1])
  );
endmodule

module DEC3x8(EN, A, SEL);
  input EN;
  wire EN;
  input [2:0] A;
  wire [2:0] A;
  output [7:0] SEL;
  wire [7:0] SEL;
  wire [2:0] A_buf;
  wire EN_buf;
  sky130_fd_sc_hd__clkbuf_4 \ABUF[0]  (
    .A(A[0]),
    .X(A_buf[0])
  );
  sky130_fd_sc_hd__clkbuf_4 \ABUF[1]  (
    .A(A[1]),
    .X(A_buf[1])
  );
  sky130_fd_sc_hd__clkbuf_4 \ABUF[2]  (
    .A(A[2]),
    .X(A_buf[2])
  );
  sky130_fd_sc_hd__nor4b_4 AND0 (
    .A(A_buf[0]),
    .B(A_buf[1]),
    .C(A_buf[2]),
    .D_N(EN_buf),
    .Y(SEL[0])
  );
  sky130_fd_sc_hd__and4bb_4 AND1 (
    .A_N(A_buf[2]),
    .B_N(A_buf[1]),
    .C(A_buf[0]),
    .D(EN_buf),
    .X(SEL[1])
  );
  sky130_fd_sc_hd__and4bb_4 AND2 (
    .A_N(A_buf[2]),
    .B_N(A_buf[0]),
    .C(A_buf[1]),
    .D(EN_buf),
    .X(SEL[2])
  );
  sky130_fd_sc_hd__and4b_4 AND3 (
    .A_N(A_buf[2]),
    .B(A_buf[1]),
    .C(A_buf[0]),
    .D(EN_buf),
    .X(SEL[3])
  );
  sky130_fd_sc_hd__and4bb_4 AND4 (
    .A_N(A_buf[0]),
    .B_N(A_buf[1]),
    .C(A_buf[2]),
    .D(EN_buf),
    .X(SEL[4])
  );
  sky130_fd_sc_hd__and4b_4 AND5 (
    .A_N(A_buf[1]),
    .B(A_buf[0]),
    .C(A_buf[2]),
    .D(EN_buf),
    .X(SEL[5])
  );
  sky130_fd_sc_hd__and4b_4 AND6 (
    .A_N(A_buf[0]),
    .B(A_buf[1]),
    .C(A_buf[2]),
    .D(EN_buf),
    .X(SEL[6])
  );
  sky130_fd_sc_hd__and4_4 AND7 (
    .A(A_buf[0]),
    .B(A_buf[1]),
    .C(A_buf[2]),
    .D(EN_buf),
    .X(SEL[7])
  );
  sky130_fd_sc_hd__clkbuf_4 ENBUF (
    .A(EN),
    .X(EN_buf)
  );
endmodule

module EBUFN_2(A, TE_B, Z);
  input A;
  wire A;
  input TE_B;
  wire TE_B;
  output Z;
  wire Z;
  sky130_fd_sc_hd__ebufn_2 __cell__ (
    .A(A),
    .TE_B(TE_B),
    .Z(Z)
  );
endmodule

module RAM32(CLK, WE0, EN0, A0, Di0, Do0);
  input CLK;
  wire CLK;
  input [3:0] WE0;
  wire [3:0] WE0;
  input EN0;
  wire EN0;
  input [4:0] A0;
  wire [4:0] A0;
  input [31:0] Di0;
  wire [31:0] Di0;
  output [31:0] Do0;
  wire [31:0] Do0;
  wire [31:0] _0_;
  wire [31:0] _1_;
  wire [3:0] _2_;
  wire [3:0] _3_;
  wire [31:0] _4_;
  wire [31:0] _5_;
  wire [31:0] _6_;
  wire [31:0] _7_;
  wire [0:0] _8_;
  wire [0:0] _9_;
  wire A0_4_reg;
  wire [4:0] A0_buf;
  wire [31:0] Di0_buf;
  wire [31:0] \Do0_pre[0] ;
  wire [31:0] \Do0_pre[1] ;
  wire EN0_buf;
  wire [1:0] SEL0;
  wire SELCLK;
  wire [3:0] WE0_buf;
  CLKBUF_4 \A0BUF[0]  (
    .A(A0[0]),
    .X(A0_buf[0])
  );
  CLKBUF_4 \A0BUF[1]  (
    .A(A0[1]),
    .X(A0_buf[1])
  );
  CLKBUF_4 \A0BUF[2]  (
    .A(A0[2]),
    .X(A0_buf[2])
  );
  CLKBUF_4 \A0BUF[3]  (
    .A(A0[3]),
    .X(A0_buf[3])
  );
  CLKBUF_4 \A0BUF[4]  (
    .A(A0[4]),
    .X(A0_buf[4])
  );
  DEC1x2 DEC0 (
    .A(A0_buf[4]),
    .EN(EN0_buf),
    .SEL(SEL0)
  );
  CLKBUF_16 \DIBUF[0]  (
    .A(Di0[0]),
    .X(Di0_buf[0])
  );
  CLKBUF_16 \DIBUF[10]  (
    .A(Di0[10]),
    .X(Di0_buf[10])
  );
  CLKBUF_16 \DIBUF[11]  (
    .A(Di0[11]),
    .X(Di0_buf[11])
  );
  CLKBUF_16 \DIBUF[12]  (
    .A(Di0[12]),
    .X(Di0_buf[12])
  );
  CLKBUF_16 \DIBUF[13]  (
    .A(Di0[13]),
    .X(Di0_buf[13])
  );
  CLKBUF_16 \DIBUF[14]  (
    .A(Di0[14]),
    .X(Di0_buf[14])
  );
  CLKBUF_16 \DIBUF[15]  (
    .A(Di0[15]),
    .X(Di0_buf[15])
  );
  CLKBUF_16 \DIBUF[16]  (
    .A(Di0[16]),
    .X(Di0_buf[16])
  );
  CLKBUF_16 \DIBUF[17]  (
    .A(Di0[17]),
    .X(Di0_buf[17])
  );
  CLKBUF_16 \DIBUF[18]  (
    .A(Di0[18]),
    .X(Di0_buf[18])
  );
  CLKBUF_16 \DIBUF[19]  (
    .A(Di0[19]),
    .X(Di0_buf[19])
  );
  CLKBUF_16 \DIBUF[1]  (
    .A(Di0[1]),
    .X(Di0_buf[1])
  );
  CLKBUF_16 \DIBUF[20]  (
    .A(Di0[20]),
    .X(Di0_buf[20])
  );
  CLKBUF_16 \DIBUF[21]  (
    .A(Di0[21]),
    .X(Di0_buf[21])
  );
  CLKBUF_16 \DIBUF[22]  (
    .A(Di0[22]),
    .X(Di0_buf[22])
  );
  CLKBUF_16 \DIBUF[23]  (
    .A(Di0[23]),
    .X(Di0_buf[23])
  );
  CLKBUF_16 \DIBUF[24]  (
    .A(Di0[24]),
    .X(Di0_buf[24])
  );
  CLKBUF_16 \DIBUF[25]  (
    .A(Di0[25]),
    .X(Di0_buf[25])
  );
  CLKBUF_16 \DIBUF[26]  (
    .A(Di0[26]),
    .X(Di0_buf[26])
  );
  CLKBUF_16 \DIBUF[27]  (
    .A(Di0[27]),
    .X(Di0_buf[27])
  );
  CLKBUF_16 \DIBUF[28]  (
    .A(Di0[28]),
    .X(Di0_buf[28])
  );
  CLKBUF_16 \DIBUF[29]  (
    .A(Di0[29]),
    .X(Di0_buf[29])
  );
  CLKBUF_16 \DIBUF[2]  (
    .A(Di0[2]),
    .X(Di0_buf[2])
  );
  CLKBUF_16 \DIBUF[30]  (
    .A(Di0[30]),
    .X(Di0_buf[30])
  );
  CLKBUF_16 \DIBUF[31]  (
    .A(Di0[31]),
    .X(Di0_buf[31])
  );
  CLKBUF_16 \DIBUF[3]  (
    .A(Di0[3]),
    .X(Di0_buf[3])
  );
  CLKBUF_16 \DIBUF[4]  (
    .A(Di0[4]),
    .X(Di0_buf[4])
  );
  CLKBUF_16 \DIBUF[5]  (
    .A(Di0[5]),
    .X(Di0_buf[5])
  );
  CLKBUF_16 \DIBUF[6]  (
    .A(Di0[6]),
    .X(Di0_buf[6])
  );
  CLKBUF_16 \DIBUF[7]  (
    .A(Di0[7]),
    .X(Di0_buf[7])
  );
  CLKBUF_16 \DIBUF[8]  (
    .A(Di0[8]),
    .X(Di0_buf[8])
  );
  CLKBUF_16 \DIBUF[9]  (
    .A(Di0[9]),
    .X(Di0_buf[9])
  );
  \$paramod\MUX2x1\WIDTH=32'00000000000000000000000000100000  Do0MUX (
    .A0(_4_),
    .A1(_5_),
    .S(A0_4_reg),
    .X(Do0)
  );
  CLKBUF_4 EN0BUF (
    .A(EN0),
    .X(EN0_buf)
  );
  sky130_fd_sc_hd__dlclkp_1 SELCG (
    .CLK(CLK),
    .GATE(EN0),
    .GCLK(SELCLK)
  );
  sky130_fd_sc_hd__dfxtp_1 SELREG (
    .CLK(SELCLK),
    .D(A0_buf[4]),
    .Q(A0_4_reg)
  );
  \$paramod$0a04d2ca855f7a52b7b0f8269f16a7f2c6677e46\RAM16  \SLICE_16[0].RAM16  (
    .A0(_2_),
    .CLK(CLK),
    .Di0(Di0_buf),
    .Do0(_6_),
    .EN0(_8_),
    .WE0(WE0_buf)
  );
  \$paramod$0a04d2ca855f7a52b7b0f8269f16a7f2c6677e46\RAM16  \SLICE_16[1].RAM16  (
    .A0(_3_),
    .CLK(CLK),
    .Di0(Di0_buf),
    .Do0(_7_),
    .EN0(_9_),
    .WE0(WE0_buf)
  );
  CLKBUF_2 \WEBUF[0]  (
    .A(WE0[0]),
    .X(WE0_buf[0])
  );
  CLKBUF_2 \WEBUF[1]  (
    .A(WE0[1]),
    .X(WE0_buf[1])
  );
  CLKBUF_2 \WEBUF[2]  (
    .A(WE0[2]),
    .X(WE0_buf[2])
  );
  CLKBUF_2 \WEBUF[3]  (
    .A(WE0[3]),
    .X(WE0_buf[3])
  );
  assign _1_ = _7_;
  assign \Do0_pre[1] = _1_;
  assign _0_ = _6_;
  assign \Do0_pre[0] = _0_;
  assign _8_ = SEL0[0];
  assign _2_ = A0_buf[3:0];
  assign _9_ = SEL0[1];
  assign _3_ = A0_buf[3:0];
  assign _4_ = \Do0_pre[0] ;
  assign _5_ = \Do0_pre[1] ;
endmodule
